name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*
permissions:
  contents: write
  packages: write
jobs:
  android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - name: Build apk
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_SHA256: ${{ secrets.KEYSTORE_SHA256 }}
        run: flutter build apk --split-per-abi --release
      - uses: actions/upload-artifact@v4
        with:
          name: "app-arm64-v8a-release.apk"
          path: "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
      - uses: actions/upload-artifact@v4
        with:
          name: "app-armeabi-v7a-release.apk"
          path: "build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk"
      - uses: actions/upload-artifact@v4
        with:
          name: "app-x86_64-release.apk"
          path: "build/app/outputs/flutter-apk/app-x86_64-release.apk"
      - name: Debug API call
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: |
          curl -v -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{"tag_name":"${{ github.ref_name }}","name":"Release ${{ github.ref_name }}","draft":false,"prerelease":false}'
#      - name: Upload assets
#        uses: softprops/action-gh-release@v1
##        env:
##          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          token: ${{ secrets.RELEASE_TOKEN }}
#          files: |
#            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
#            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
#            build/app/outputs/flutter-apk/app-x86_64-release.apk